name: Build LaTeX document
on:
  push:
    branches: [ master ]

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: fontconfig
          pre_compile: "mkdir ~/.fonts && wget https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-Regular.ttf && wget https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-Bold.ttf && wget https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-Italic.ttf && wget https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-BoldItalic.ttf && mv SourceSansPro-* ~/.fonts/ && fc-cache -f -v"
          root_file: teilnahmebedingungen-cd-shoeneweideberlin.tex
          latexmk_use_xelatex: true
          
      - name: Deploy
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'teilnahmebedingungen-cd-shoeneweideberlin.pdf'
          destination_repo: 'Coderdojo-Schoeneweide/website-hugo'
          destination_folder: 'static/docs'
          user_email: 'build-latex@github-actions.com'
          user_name: 'Build LaTeX'
          commit_message: 'Updated Teilnahmebedingungen PDF'
