name: Build LaTeX document
on:
  push:
    branches: [ master ]

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: fontconfig
          pre_compile: "mkdir ~/.fonts && wget https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-Regular.ttf && wget https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-Bold.ttf && wget https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-Italic.ttf && wget https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-BoldItalic.ttf && mv SourceSansPro-* ~/.fonts/ && fc-cache -f -v"
          root_file: teilnahmebedingungen-cd-shoeneweideberlin.tex
          latexmk_use_xelatex: true
          
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.API_TOKEN_GITHUB }}
          name: id_ed25519
      
      - name: Deploy
        run: |
          ls -a
          pwd
